### PR TITLE
Support PS 2342

### PR DESCRIPTION
**Pull request by felixn**
Credit for most of the multi-channel support goes to https://github.com/xolotl90/ps2000/blob/master/ps2000.py

### CODE REVIEW

**Comment by felixn** [comment]
Hi @marcj71, have you had a chance to look at the changes?

**Review by marcj71 — APPROVED** [review]
Thanks for your contribution, felixn! I don't have a PS2342 model to test these changes, but I trust you're using it with some success :)

**Comment by marcj71** [comment]
Merged PS 2342 support

**Comment by felixn** [comment]
Hi Marc, thanks for the positive feedback. Yep. we're using the PS2342 successfully every day :)

I'm not sure what went wrong, but it looks like you didn't actually merge the changes. 
The latest commit in your repo is still from Nov 2019:
https://github.com/marcj71/ps2000/commits/master

**Comment by felixn** [comment]
Hi @marcj71, it looks like you closed the Pull Request without merging the changes to master.
Should I open another pull request?

**Pull request closed without merging**
